const String appLogo = 'assets/icon/icon.png';
const String appFeatureImage = 'assets/icon/feature_store.jpg';

const List<String>imgSignLink=['https://xpgt.thuvienphapluat.vn/uploads/bienbao/S.501.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/S.503d.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/S.503e.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/S.503c.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/S.502.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/S.504.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/S.503f.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/S.503b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/S.503a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.105.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.124a2.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/S.505c.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/S.H,3c.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/S.505b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/S.505a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/S.G,7.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/S.510.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/S.509b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/S.509a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/S.508b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/S.508a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/S.507.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/S.506b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/S.506a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/S.G,11a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/S.G,9b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/S.G,8.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.102.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.101.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/S.H,6.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/S.G,12b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/S.G,12a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/S.G,11c.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.301b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.118.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.301d.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.117.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.301c.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.116.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.115.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.114.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.301a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.123b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.123a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.403b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.403a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.121.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.310c.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.310b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.310a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.309.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.308b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.308a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.202a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.202b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.201a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.201c.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.203a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.201b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.201d.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/DP.133.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.203c.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.203b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.207c.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.207b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.207a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.206.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.205e.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.140.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.139.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.205d.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.138.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.205c.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.137.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.136.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.302b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.119.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.301e.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.120.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.302a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.301i.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.301h.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.303.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.302c.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.403c.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.124a1.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.124d.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.124c.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.124b1.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.403d.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.126.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.125.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.124f.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.124e.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.243c.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.243b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.243a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.242b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.242a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.241.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.240.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.239.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.238.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.237.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.236.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.406.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.401.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.402.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.405a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.405b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.405c.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.407a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.247.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.246c.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.246b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.246a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.245b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.245a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.244.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.407c.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.407b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.410.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.409.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.408a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.408.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.414d.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.414c.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.414b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.414a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.413c.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.413b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.413a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.235.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.234.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.233.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.232.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.231.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.230.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.229.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.228d.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.228c.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.228b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.228a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.227.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.226.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.225.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.224.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.223b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.223a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.222b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.222a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.221b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.221a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.220.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.301f.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.219.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.218.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.217.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.216b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.216a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.215c.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.412k.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.412i.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.207d.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.412n.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.412m.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.412l.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.412j.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.207i.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.207h.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.207g.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.207f.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.207e.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.E,10c.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.211b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.E,10d.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.E,11a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.E,11b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.215b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.215a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.214.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.213.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.212.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.421.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.415.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.412p.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.412o.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.E,9a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.209.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.208.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.207l.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.207k.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.420.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.128.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.127d1.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.404c.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.404f.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.411.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.129.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.404e.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.404d.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.E,10b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.E,10a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.E,9d.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.E,9c.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.E,9b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.211a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.210.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.205b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/DP.135.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.205a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/DP.134.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/W.204.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.412h.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.132.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.412g.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.412f.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.412e.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.412d.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.412c.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.412b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.412a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.131c.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.131b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.131a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.130.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.404b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.404a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.127b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.403f.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.403e.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.127a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.127.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.304.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.307.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.306.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.305.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/S.H,3b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/S.H,3a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.449.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.448.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.447d.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.447c.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.447b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.447a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.446.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.445h.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.445g.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.445f.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.445e.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.445d.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.445c.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.445b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.445a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.444m.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.444l.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.444k.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.444j.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.444i.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.444h.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.444g.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.444f.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.444e.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.444d.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.444c.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.444b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.444a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.443.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.442.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.441c.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.441b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.441a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.440.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.439.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.436.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.435.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.434b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.434a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.433e.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.433d.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.433c.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.433b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.433a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.432.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.431.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.430.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.429.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.428.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.427b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.427a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.426.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.425.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.424d.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.424c.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.424b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.424a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.423c.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.423b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.423a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.422b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.422a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.419b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.419a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.418.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.417c.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.417b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.417a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.416.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/I.415.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.113.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/R.122.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.112.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.111d.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.111b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.127d2.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.111a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.110b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.110a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.109.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.108a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.108.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.107b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.107a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.107.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.106c.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.106b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.106a.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.124b2.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.104.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.103c.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.103b.png',
  'https://xpgt.thuvienphapluat.vn/uploads/bienbao/P.103a.png',
];
const List<String> imgSignContent=['Để thông báo chiều dài đoạn đường nguy hiểm hoặc cấm hoặc hạn chế bên dưới một số biển báo nguy hiểm, biển báo cấm hoặc hạn chế.',
  'Để chỉ hướng tác dụng của biển là hướng song song với chiều đi.',
  'Để chỉ đồng thời hai hướng tác dụng (trước và sau) nơi đặt biển báo nhắc lại lệnh cấm dừng và cấm đỗ xe.',
  'Để chỉ hướng tác dụng của biển là hướng vuông góc với chiều đi.',
  'Để thông báo khoảng cách thực tế từ vị trí đặt biển đến đối tượng báo hiệu ở phía trước. Con số trên biển ghi theo đơn vị mét (m) và lấy chẵn đến hàng chục mét.',
  'Để chỉ làn đường chịu hiệu lực của biển báo hay đèn tín hiệu.',
  'Để chỉ hướng tác dụng của biển là hướng song song với chiều đi.',
  'Để chỉ đồng thời hai hướng tác dụng (trái và phải).',
  'Để chỉ hướng tác dụng của biển là hướng vuông góc với chiều đi.',
  'Để báo đường cấm các loại xe cơ giới và xe máy đi qua.',
  'Để báo cấm các loại xe quay đầu (theo kiểu chữ U). Chiều mũi tên phù hợp với chiều cấm quay đầu xe. Biển số P',
  'Để chỉ các loại xe tải có tải trọng trục lớn nhất cho phép tương ứng với mỗi loại trục (trục đơn, trục kép, trục ba).',
  'Để chỉ hướng tác dụng của biển là hướng vuông góc với chiều đi. Trên các tuyến đường đối ngoại và các tuyến đường có nhiều người đi lại.',
  'Để chỉ các loại xe tải chịu hiệu lực của biển báo và tải trọng toàn bộ xe cho phép (bao gồm tải trọng bản thân xe và khối lượng chuyên chở cho phép) tương ứng với mỗi loại xe không phụ thuộc vào số lượng trục.',
  'Để chỉ loại xe chịu hiệu lực của biển báo cấm, biển hiệu lệnh hay biển chỉ dẫn. ',
  'Để chỉ dẫn tới địa điểm cắm trại.',
  'Để cảnh báo đường trơn, có tuyết trong những ngày trời có tuyết.',
  'Cấm đỗ xe.',
  'Biển này chỉ rõ chiều cao cho các phương tiện đi qua an toàn.',
  'Nhằm quy định phạm vi thời gian hiệu lực của các biển báo cấm, biển hiệu lệnh cho phù hợp yêu cầu.',
  'Nhằm quy định phạm vi thời gian hiệu lực của các biển báo cấm, biển hiệu lệnh cho phù hợp yêu cầu.',
  'Để báo trước cho người tham gia giao thông biết chỗ rẽ nguy hiểm và để chỉ hướng rẽ.',
  'Để chỉ dẫn cho người tham gia giao thông trên đường này biết hướng đường ưu tiên ở ngã tư.',
  'Để chỉ dẫn cho người tham gia giao thông trên đường này biết hướng đường ưu tiên ở ngã tư.',
  'Chỉ dẫn số lượng làn và hướng đi cho từng làn',
  'Chỉ dẫn tới điểm đỗ xe dành cho lái xe muốn sử dụng phương tiện công cộng',
  'Chỉ dẫn tới nhà trọ',
  'Để báo đường cấm các loại xe (cơ giới và thô sơ) đi vào theo chiều đặt biển, trừ các xe được ưu tiên theo quy định. Người đi bộ được phép đi trên vỉa hè hoặc lề đường.',
  'Để báo đường cấm các loại phương tiện đi lại cả hai hướng, trừ các xe được ưu tiên theo quy định.',
  'Để chỉ các trường hợp mà biển cấm hoặc hạn chế được coi là không áp dụng đặc biệt cho một nhóm đối tượng tham gia giao thông nào đó.',
  'Để chỉ dẫn cho lái xe biết làn đường không lưu thông.',
  'Biển chỉ dẫn làn đường không lưu thông',
  'Để thông báo cho lái xe số làn và hướng đi của từng làn xe, các biển này phải có số mũi tên bằng số lượng làn xe đi cùng hướng và phải chỉ dẫn số lượng làn xe của hướng đi sắp tới.',
  'Nhằm chỉ hướng cho phép xe đi ngang qua nơi đường giao nhau và ngăn chặn hướng đi ngược chiều trên đường phố với đường một chiều. Biển bắt buộc người tham gia giao thông chỉ được phép rẽ phải hoặc rẽ trái ở phạm vi nơi đường giao nhau trước mặt biển.',
  'Để báo hạn chế chiều ngang của xe.',
  'Biển bắt buộc người tham gia giao thông chỉ được phép rẽ phải hoặc rẽ trái ở phạm vi nơi đường giao nhau đằng sau mặt biển.',
  'Để báo hạn chế chiều cao của xe.',
  'Nhằm chỉ hướng cho phép xe đi ngang qua nơi đường giao nhau và ngăn chặn hướng đi ngược chiều trên đường phố với đường một chiều. Biển bắt buộc người tham gia giao thông chỉ được phép rẽ phải hoặc rẽ trái ở phạm vi nơi đường giao nhau trước mặt biển.',
  'Để báo đường cấm các loại xe (cơ giới và thô sơ) kể cả các xe được ưu tiên theo quy định, có tải trọng toàn bộ xe (cả xe và hàng) phân bổ trên một trục bất kỳ của xe (tải trọng trục xe) vượt quá trị số ghi trên biển đi qua.',
  'Để báo đường cấm các loại xe (cơ giới và thô sơ) kể cả các xe được ưu tiên theo quy định, có tải trọng toàn bộ xe (tải trọng bản thân xe cộng với khối lượng chuyên chở) vượt quá trị số ghi trên biển đi qua.',
  'Để báo đường cấm súc vật vận tải hàng hóa hoặc hành khách dù kéo xe hay chở trên lưng đi qua.',
  'Khi đặt biển số R.301a ở trước nơi đường giao nhau thì hiệu lực tác dụng của biển là ở phạm vi khu vực nơi đường giao nhau phía sau biển tức là cấm xe rẽ phải hay rẽ trái. Nếu biển này đặt ở sau nơi đường giao nhau (bắt đầu vào đoạn đường phố) thì hiệu lực tác dụng của biển là từ vị trí đặt biển đến nơi đường giao nhau. Trong trường hợp này cấm rẽ trái và quay đầu trong vùng tác dụng của biển, chỉ cho phép rẽ phải vào cổng nhà hoặc ngõ phố có trên đoạn đường từ nơi đường giao nhau đặt biển đến nơi đường giao nhau tiếp theo.',
  'Để báo cấm rẽ trái hoặc rẽ phải (theo hướng mũi tên chỉ) ở những vị trí đường giao nhau. Biển không có giá trị cấm quay đầu xe. Biển có hiệu lực cấm các loại xe (cơ giới và thô sơ) rẽ sang phía phải trừ các xe được ưu tiên theo quy định.',
  'Để báo cấm rẽ trái hoặc rẽ phải (theo hướng mũi tên chỉ) ở những vị trí đường giao nhau. Biển không có giá trị cấm quay đầu xe. Biển có hiệu lực cấm các loại xe (cơ giới và thô sơ) rẽ sang phía trái trừ các xe được ưu tiên theo quy định.',
  'Để báo hiệu bắt đầu đường dành cho các loại ôtô, xe máy (kể cả xe gắn máy) đi lại.',
  'Để báo hiệu bắt đầu đường dành cho các loại ôtô đi lại.',
  'Để báo xe ôtô phải đi cách nhau một khoảng tối thiểu. Số ghi trên biển cho biết khoảng cách tối thiểu tính bằng mét. Biển có hiệu lực cấm các xe ôtô kể cả xe được ưu tiên theo quy định đi cách nhau một cự ly nhỏ hơn trị số ghi trên biển báo.',
  'Để báo cho các loại xe chở hàng nguy hiểm phải đi theo hướng quy định. Xe bắt buộc rẽ phải.',
  ' Để báo cho các loại xe chở hàng nguy hiểm phải đi theo hướng quy định. Xe bắt buộc đi thẳng.',
  'Để báo cho các loại xe chở hàng nguy hiểm phải đi theo hướng quy định. Xe bắt buộc phải rẽ trái.',
  'Biểu thị xe cộ đi đến vị trí cắm biển đó thì phải ấn còi. ',
  'Biểu thị phía trước có cầu vượt, xe có thể đi thẳng hoặc theo chỉ dẫn trên hình vẽ để rẽ phải.',
  'Biểu thị phía trước có cầu vượt, xe có thể đi thẳng hoặc theo chỉ dẫn trên hình vẽ để rẽ trái.',
  'Báo trước sắp đến hai chỗ ngoặt ngược chiều nhau liên tiếp, ở gần nhau trong đó có ít nhất một chỗ ngoặt nguy hiểm mà chỗ ngoặt đầu tiên hướng vòng bên trái.',
  'Báo trước sắp đến hai chỗ ngoặt ngược chiều nhau liên tiếp, ở gần nhau trong đó có ít nhất một chỗ ngoặt nguy hiểm mà chỗ ngoặt đầu tiên hướng vòng bên phải.',
  'Báo trước sắp đến một chỗ ngoặt nguy hiểm vòng bên trái.',
  'Báo trước sắp đến chỗ ngoặt nguy hiểm có khả năng gây lật các xe có trọng tâm cao và tải trọng lớn như xe tải, xe buýt giường nằm, xe chở chất lỏng, v.v... có nguy cơ lật xe bên phải khi đường cong vòng sang trái.',
  'Báo trước sắp đến một đoạn đường bị thu hẹp cả hai bên.',
  'Báo trước sắp đến một chỗ ngoặt nguy hiểm vòng bên phải.',
  'Báo trước sắp đến chỗ ngoặt nguy hiểm có khả năng gây lật các xe có trọng tâm cao và tải trọng lớn như xe tải, xe buýt giường nằm, xe chở chất lỏng, v.v... có nguy cơ lật xe bên trái khi đường cong vòng bên phải.',
  'Để báo hết đoạn đường cấm vượt. Biển có tác dụng báo cho người tham gia giao thông biết hiệu lực của các biển số P.125 và biển số P.126 hết tác dụng. Các xe cơ giới được phép vượt nhau nhưng phải theo quy định về điều kiện cho phép vượt nhau.',
  'Báo trước sắp đến một đoạn đường bị thu hẹp về phía phải.',
  'Báo trước sắp đến một đoạn đường bị thu hẹp về phía trái.',
  'Đặt trên đường ưu tiên, để báo trước sắp đến nơi giao nhau với đường không ưu tiên',
  'Đặt trên đường ưu tiên, để báo trước sắp đến nơi giao nhau với đường không ưu tiên',
  'Đặt trên đường ưu tiên, để báo trước sắp đến nơi giao nhau với đường không ưu tiên',
  'Báo trước nơi giao nhau có bố trí đảo an toàn ở giữa nút giao, các loại xe qua nút giao phải đi vòng xuyến quanh đảo an toàn theo chiều mũi tên',
  'Báo trước sắp đến nơi giao nhau cùng mức của các tuyến đường cùng cấp (không có đường nào ưu tiên) trên cùng một mặt bằng.',
  'Để báo đường cấm xe công nông.',
  'Biểu thị đường qua nút giao cấm tất cả các loại xe (cơ giới và thô sơ) đi thẳng, rẽ phải.',
  'Báo trước sắp đến nơi giao nhau cùng mức của các tuyến đường cùng cấp (không có đường nào ưu tiên) trên cùng một mặt bằng.',
  'Biểu thị đường qua nút giao cấm tất cả các loại xe (cơ giới và thô sơ) đi thẳng, rẽ trái.',
  'Báo trước sắp đến nơi giao nhau cùng mức của các tuyến đường cùng cấp (không có đường nào ưu tiên) trên cùng một mặt bằng.',
  'Các ngả đường phía trước cấm tất cả các loại xe (cơ giới và thô sơ) rẽ trái hay rẽ phải. ',
  'Đường ở phía trước cấm tất cả các loại xe (cơ giới và thô sơ) đi thẳng. ',
  'Để báo các loại xe (cơ giới và thô sơ) hướng đi để qua một chướng ngại vật. Chỉ được vòng sang trái.',
  'Để báo đường cấm các loại xe (cơ giới và thô sơ) kể cả các xe được ưu tiên theo quy định, có độ dài toàn bộ kể cả xe và hàng lớn hơn trị số ghi trên biển đi qua.',
  'Biển bắt buộc người tham gia giao thông chỉ được phép rẽ phải hoặc rẽ trái ở phạm vi nơi đường giao nhau đằng sau mặt biển.',
  'Để báo đường cấm các loại xe cơ giới kéo theo moóc kể cả ôtô sơ-mi-rơ-moóc và các loại xe được ưu tiên kéo moóc theo luật nhà nước quy định, có độ dài toàn bộ kể cả xe, moóc và hàng lớn hơn trị số ghi trên biển đi qua.',
  'Để báo các loại xe (cơ giới và thô sơ) hướng đi để qua một chướng ngại vật. Chỉ được vòng sang phải',
  'Nhằm ngăn ngừa chuyển động ngược chiều trên đường phố với đường một chiều. Biển bắt buộc người tham gia giao thông chỉ được phép rẽ trái, quay đầu hoặc rẽ phải ở phạm vi nơi đường giao nhau trước mặt biển',
  'Người tham gia giao thông chỉ được phép đi thẳng hay rẽ trái và được phép quay đầu xe để đi theo hướng ngược lại.',
  'Để báo cho các loại xe (thô sơ và cơ giới) phải chạy vòng theo đảo an toàn ở nơi đường giao nhau . Biển có hiệu lực bắt buộc các loại xe muốn chuyển hướng phải chạy vòng theo đảo an toàn theo hướng mũi tên.',
  'Để báo các loại xe (cơ giới và thô sơ) hướng đi để qua một chướng ngại vật. Phải vòng sang trái hoặc sang phải mà lựa chọn kiểu biển cho phù hợp.',
  'Để báo hiệu bắt đầu đường dành cho xe buýt.',
  'Để báo cấm các loại xe quay đầu (theo kiểu chữ U). Chiều mũi tên phù hợp với chiều cấm quay đầu xe. Biển số P.124a có hiệu lực cấm các loại xe (cơ giới và thô sơ) trừ các xe được ưu tiên theo quy định. Biển không có giá trị cấm rẽ trái để đi sang hướng đường khác.',
  'Cam re phai va quay dau xe”Để báo cấm các loại xe rẽ phải đồng thời cấm quay đầu.',
  'Cam re trai va quay dau xe”Để báo cấm các loại xe rẽ trái đồng thời cấm quay đầu.',
  'Để báo cấm xe ôtô quay đầu (theo kiểu chữ U). Chiều mũi tên phù hợp với chiều cấm xe ô tô quay đầu. Biển số P.124b có hiệu lực cấm xe ôtô và xe máy 3 bánh (side car) quay đầu (theo kiểu chữ U) trừ các xe được ưu tiên theo quy định. Biển không có giá trị cấm rẽ trái để đi sang hướng đường khác.',
  'Để báo hiệu bắt đầu đường dành cho xe ôtô con.',
  'Cấm ôtô tải vượt. Biển có hiệu lực cấm các loại ôtô tải có khối lượng chuyên chở (theo Giấy chứng nhận kiểm định an toàn kỹ thuật và bảo vệ môi trường phương tiện giao thông cơ giới đường bộ) lớn hơn 3.500 kg kể cả các xe được ưu tiên theo quy định vượt xe cơ giới khác. Được phép vượt xe máy 2 bánh, xe gắn máy. Biển không có giá trị cấm các loại xe cơ giới khác vượt nhau và vượt ôtô tải.',
  'Để báo cấm các loại xe cơ giới vượt nhau. Biển có hiệu lực cấm tất cả các loại xe cơ giới vượt nhau (kể cả xe được ưu tiên theo quy định) nhưng được phép vượt xe máy 2 bánh, xe gắn máy.',
  'Cam o to re phai va quay dau xe”Để báo cấm xe ôtô rẽ phải và đồng thời cấm quay đầu.',
  'Cam o to re trai va quay dau xe”Để báo cấm xe ôtô rẽ trái và đồng thời cấm quay đầu.',
  'Được đặt ở nơi cách ray gần nhất nơi giao đường sắt 150 m để báo trước sắp đến vị trí giao cắt đường bộ với đường sắt cùng mức, không vuông góc và không có người gác, không có rào chắn.',
  'Được đặt ở nơi cách ray gần nhất nơi giao đường sắt 100 m để báo trước sắp đến vị trí giao cắt đường bộ với đường sắt cùng mức, không vuông góc và không có người gác, không có rào chắn.',
  'Được đặt ở nơi cách ray gần nhất nơi giao đường sắt 50 m để báo trước sắp đến vị trí giao cắt đường bộ với đường sắt cùng mức, không vuông góc và không có người gác, không có rào chắn.',
  'Để chỉ chỗ đường sắt giao vuông góc đường bộ. Và tại chỗ giao nhau, đường sắt có từ hai cặp đường ray trở lên cắt ngang đường bộ.',
  'Để chỉ chỗ đường sắt giao vuông góc đường bộ. Và tại chỗ giao nhau, đường sắt chỉ có một cặp đường ray cắt ngang đường bộ.',
  'Báo đoạn đường hay xảy ra ùn tắc giao thông.',
  'Để nhắc lái xe chú ý chuẩn bị đi vào hầm đường bộ.',
  'Báo hiệu nơi có đường dây điện cắt ngang phía trên tuyến đường.',
  'Đặt trên đường nhánh nhập vào đường cao tốc để báo cho các phương tiện đi trên đường này biết có "Đường cao tốc phía trước".',
  'Dùng để nhắc nhở lái xe phải thận trọng. Biển đặt ở trên đoạn đường sắp đến công trình có độ vồng lớn ảnh hưởng tới tầm nhìn.',
  'Báo trước sắp kết thúc đoạn đường có chiều đi và chiều về phân biệt bằng dải phân cách cứng.',
  'Chỉ dẫn cho người tham gia giao thông cơ giới biết mình được quyền ưu tiên đi trước trên đoạn đường hẹp.',
  'Biểu thị ưu tiên cho các phương tiện trên đường có đặt biển này được đi trước.',
  'Biểu thị hết đoạn đường quy định là ưu tiên.',
  'Chỉ lối rẽ vào đường cụt.',
  'Chỉ lối rẽ vào đường cụt.',
  'Chỉ dẫn phía trước là đường cụt.',
  'Chỉ dẫn những đoạn đường chạy một chiều.',
  'Để cảnh báo có các loại xe ôtô, máy kéo, rơ-moóc hoặc sơ-mi rơ-moóc được kéo bởi xe ôtô hoặc ôtô đầu kéo, xe máy chuyên dùng đang đỗ chiếm một phần đường xe chạy.',
  'Báo trước cho lái xe biết phía trước có chướng ngại vật, xe cần giảm tốc độ và đi theo chỉ dẫn trên biển báo.',
  'Báo trước cho lái xe biết phía trước có chướng ngại vật, xe cần giảm tốc độ và đi theo chỉ dẫn trên biển báo.',
  'Báo trước cho lái xe biết phía trước có chướng ngại vật, xe cần giảm tốc độ và đi theo chỉ dẫn trên biển báo.',
  'Dùng để nhắc lái xe giảm tốc độ đi chậm.',
  'Dùng để nhắc lái xe giảm tốc độ đi chậm.',
  'Dùng để cảnh báo nguy hiểm đoạn đường phía trước thường xảy ra tai nạn để lái xe cần đặc biệt chú ý.',
  'Chỉ dẫn những đoạn đường chạy một chiều.',
  'Chỉ dẫn những đoạn đường chạy một chiều.',
  'Chỉ dẫn khu vực được phép quay đầu xe.',
  'Chỉ dẫn vị trí được phép quay đầu xe.',
  'Chỉ dẫn những nơi được phép đỗ xe một phần trên hè phố rộng. Xe phải đỗ từ ½ thân xe trở lên trên hè phố.',
  'Chỉ dẫn những nơi được phép đỗ xe, những bãi đỗ xe, bến xe, v.v...',
  'Chỉ dẫn hướng đường đến các địa danh, khu dân cư.',
  'Chỉ dẫn hướng đường đến các địa danh, khu dân cư.',
  'Chỉ dẫn hướng đường đến các địa danh, khu dân cư.',
  'Chỉ dẫn hướng đường đến các địa danh, khu dân cư.',
  'Chỉ dẫn cho người tham gia giao thông biết ở nơi đường giao nhau rẽ trái là rẽ ra đường có làn đường dành riêng cho ô tô khách.',
  'Chỉ dẫn cho người tham gia giao thông biết ở nơi đường giao nhau rẽ phải là rẽ ra đường có làn đường dành riêng cho ô tô khách.',
  'Chỉ dẫn cho người tham gia giao thông biết đường phía trước có làn đường dành riêng cho ô tô khách theo chiều ngược lại.',
  'Báo trước sắp đến đoạn đường có chiều đi và chiều về phân biệt bằng dải phân cách cứng.',
  'Trên đường một chiều, để báo trước sắp đến vị trí giao nhau với đường hai chiều.',
  'Cảnh báo những nguy hiểm khác.',
  'Báo trước gần tới đoạn đường thường có gió ngang thổi mạnh gây nguy hiểm. Người tham gia giao thông cần phải điều chỉnh tốc độ xe chạy cho thích hợp, đề phòng gió thổi mạnh gây lật xe.',
  'Báo trước gần tới đoạn đường thường có thú rừng qua đường như đường đi qua rừng hay khu vực bảo tồn thiên nhiên cấm săn bắn, người tham gia giao thông phải đi chậm, chú ý quan sát hai bên đường và thận trọng đề phòng tai nạn.',
  'Báo trước gần tới đoạn đường thường có gia súc thả rông hoặc lùa qua ngang đường, đường ở vùng đồng cỏ của nông trường chăn nuôi, vùng thảo nguyên. Người tham gia giao thông có trách nhiệm đi chậm, quan sát và dừng lại bảo đảm cho gia súc có thể qua đường không bị nguy hiểm.',
  'Báo trước đoạn đường ở vùng sát đường băng sân bay và cắt ngang qua hướng máy bay lên xuống ở độ cao không lớn.',
  'Cảnh báo những đoạn nền đường yếu, đoạn đường đang theo dõi lún mà việc vận hành xe ở tốc độ cao có thể gây nguy hiểm.',
  'Báo trước nơi có kết cấu mặt đường rời rạc, khi phương tiện đi qua, làm cho các viên đá, sỏi băng lên gây nguy hiểm và mất an toàn cho người và phương tiện tham gia giao thông.',
  'Báo trước gần tới đoạn đường có hiện tượng đất đá từ trên ta luy dương sụt lở bất ngờ gây nguy hiểm cho xe cộ và người đi đường, đặc biệt là ở những đoạn đường miền núi.',
  'Báo trước gần tới đoạn đường có hiện tượng đất đá từ trên ta luy dương sụt lở bất ngờ gây nguy hiểm cho xe cộ và người đi đường, đặc biệt là ở những đoạn đường miền núi.',
  'Báo trước gần tới đoạn đường đang tiến hành thi công sửa chữa, cải tạo, nâng cấp có người và máy móc đang làm việc trên mặt đường. Khi gặp biển báo này tốc độ xe chạy phải giảm cho thích hợp, không gây nguy hiểm cho người và máy móc trên đoạn đường đó.',
  'Báo trước là gần tới vị trí thường có người đi xe đạp từ những đường nhỏ cắt ngang qua hoặc từ đường dành cho xe đạp đi nhập vào đường ôtô.',
  'Báo trước là gần đến đoạn đường thường có trẻ em đi ngang qua hoặc tụ tập trên đường như ở vườn trẻ, trường học, câu lạc bộ.',
  'Báo trước sắp tới phần đường dành cho người đi bộ sang qua đường. Gặp biển này các xe phải giảm tốc độ, nhường ưu tiên cho người đi bộ và chỉ được chạy xe khi không gây nguy hiểm cho người đi bộ.',
  'Báo hiệu đường đi sát vách núi ở bên phải đường để báo nguy hiểm cho người tham gia giao thông phải cẩn thận.',
  'Báo hiệu đường đi sát vách núi ở bên trái đường để báo nguy hiểm cho người tham gia giao thông phải cẩn thận.',
  'Báo những nơi lề đường không ổn định, khi xe đi vào dễ gây văng đất đá hoặc bánh xe quay tại chỗ.',
  'Báo trước sắp tới đoạn đường có thể xảy ra trơn trượt đặc biệt là khi thời tiết xấu, mưa phùn.',
  'Để cảnh báo xe đi chậm trước khi qua những điểm có gồ giảm tốc phía trước hoặc những vị trí tiếp giáp với đầu cầu, cống bị lún, võng.',
  'Báo trước sắp tới đoạn đường có mặt đường không bằng phẳng, lồi lõm gập ghềnh, ổ gà, lượn sóng.',
  'Báo trước sắp tới đoạn đường lên dốc nguy hiểm.',
  'Biển bắt buộc người tham gia giao thông chỉ được phép đi thẳng hay rẽ phải ở phạm vi nơi đường giao nhau đằng sau mặt biển.',
  'Báo trước sắp tới đoạn đường xuống dốc nguy hiểm.',
  'Báo trước sắp đến đường có cổng chắn ngang, kiểu cổng như đường hầm, cổng thành, cầu vượt đường bộ dạng cầu vòm, v.v...',
  'Báo trước sắp đến bến phà.',
  'Báo trước những vị trí có đường ngầm (đường tràn) có nguy cơ lũ quét.',
  'Báo trước những vị trí có đường ngầm (đường tràn).',
  'Báo trước sắp tới những vị trí có kè chắn vực sâu hoặc sông suối ở bên đường phía bên phải hoặc đi sát đường, cần đề phòng tình huống nguy hiểm rơi xuống vực sâu hoặc sông suối (thường có ở những chỗ ngoặt nguy hiểm).',
  'Báo hiệu kết thúc làn đường dành cho xe ôtô tải.',
  'Báo hiệu kết thúc làn đường dành cho xe ôtô khách.',
  'Đặt trên đường ưu tiên, để báo trước sắp đến nơi giao nhau với đường không ưu tiên.',
  'Báo hiệu kết thúc làn đường dành cho xe ôtô.',
  'Báo hiệu kết thúc làn đường dành cho xe buýt.',
  'Báo hiệu kết thúc làn đường dành cho xe máy.',
  'Báo hiệu kết thúc làn đường dành cho xe ôtô con.',
  'Đặt trên đường ưu tiên, để báo trước sắp đến nơi giao nhau với đường không ưu tiên.',
  'Đặt trên đường ưu tiên, để báo trước sắp đến nơi giao nhau với đường không ưu tiên.',
  'Đặt trên đường ưu tiên, để báo trước sắp đến nơi giao nhau với đường không ưu tiên.',
  'Đặt trên đường ưu tiên, để báo trước sắp đến nơi giao nhau với đường không ưu tiên.',
  'Đặt trên đường ưu tiên, để báo trước sắp đến nơi giao nhau với đường không ưu tiên.',
  'Báo hiệu hết khu vực đỗ xe.',
  'Để chỉ nơi đường bộ giao nhau cùng mức với đường tàu điện.',
  'Báo hiệu hết hạn chế tốc độ tối đa trong khu vực.',
  'Báo hiệu bắt đầu Đường hầm.',
  'Ket thuc duong hamBáo hiệu kết thúc đường hầm.',
  'Báo trước sắp tới những vị trí có kè chắn vực sâu hoặc sông suối ở bên đường phía bên trái hoặc đi sát đường, cần đề phòng tình huống nguy hiểm rơi xuống vực sâu hoặc sông suối (thường có ở những chỗ ngoặt nguy hiểm).',
  'Báo trước sắp tới những vị trí có kè chắn vực sâu hoặc sông suối ở phía trước hoặc đi sát đường, cần đề phòng tình huống nguy hiểm rơi xuống vực sâu hoặc sông suối (thường có ở những chỗ ngoặt nguy hiểm).',
  'Báo phía trước gặp cầu quay, cầu cất là loại cầu trong từng thời gian có cắt giao thông đường bộ bằng cách quay hoặc nâng nhịp thông thuyền để cho tàu thuyền qua lại.',
  'Báo trước sắp đến cầu tạm là loại cầu được làm để sử dụng tạm thời cho xe cộ qua lại.',
  'Báo trước sắp đến cầu hẹp là loại cầu có chiều rộng phần xe chạy nhỏ hơn hoặc bằng 4,50 m.',
  'Báo hiệu hết khu đông dân cư.',
  'Để báo hiệu cho người tham gia giao thông biết số lượng làn đường và loại xe được phép lưu thông trên từng làn đường theo quy định. Biển không áp dụng với các xe chuyển làn để ra vào hoặc dừng đổ bên đường. ',
  'Báo hiệu kết thúc làn đường dành cho xe đạp.',
  'Báo hiệu kết thúc làn đường dành cho xe xe máy và xe đạp.',
  'Báo hiệu cấm đỗ xe trong khu vực.',
  'Báo trước nơi giao nhau có điều khiển giao thông bằng tín hiệu đèn trong trường hợp người tham gia giao thông khó quan sát thấy đèn để kịp thời xử lý.',
  'Đặt trên đường không ưu tiên, để báo trước sắp đến nơi giao nhau với đường ưu tiên.',
  'Đặt trên đường ưu tiên, để báo trước sắp đến nơi giao nhau với đường không ưu tiên.',
  'Đặt trên đường ưu tiên, để báo trước sắp đến nơi giao nhau với đường không ưu tiên.',
  'Để báo hiệu bắt đầu đoạn đường vào phạm vi khu đông dân cư. Biển có tác dụng báo cho người tham gia giao thông biết phạm vi phải tuân theo những quy định đi đường được áp dụng ở khu đông dân cư.',
  'Để báo cấm các loại xe sử dụng còi.',
  'Đến hết đoạn đường hạn chế tốc độ tối đa cho phép.',
  'Báo hiệu hết đoạn đường dành cho xe buýt.',
  'Báo hiệu hết đoạn đường dành cho xe máy và xe đạp.',
  'Để báo hiệu cho người tham gia giao thông biết số lượng làn đường trên mặt đường và hướng đi trên mỗi làn đường theo vạch kẻ đường. Biển có tác dụng bắt buộc người tham gia giao thông phải đi đúng làn đường đã được chỉ dẫn hướng phù hợp với hành trình của xe.',
  'Để báo nơi đặt trạm kiểm tra; các loại phương tiện vận tải qua đó phải dừng lại để làm thủ tục kiểm tra, kiểm soát theo quy định.',
  'Báo hiệu hết đoạn đường dành cho xe máy.',
  'Báo hiệu hết đoạn đường dành cho xe ôtô con.',
  ' Báo hiệu hết cấm đỗ xe theo giờ trong khu vực.',
  'Báo hiệu hết cấm đỗ xe trong khu vực.',
  'Báo hiệu hạn chế tốc độ tối đa trong khu vực.',
  'Báo hiệu khu vực đỗ xe.',
  'Báo hiệu cấm đỗ xe theo giờ trong khu vực.',
  'Báo trước sắp đến chỗ giao nhau giữa đường bộ và đường sắt không có rào chắn, không có người điều khiển giao thông.',
  'Báo trước sắp đến chỗ giao nhau giữa đường bộ và đường sắt có rào chắn kín hay rào chắn nửa kín và có nhân viên ngành đường sắt điều khiển giao thông.',
  'Báo trước sắp đến nơi giao nhau cùng mức của các tuyến đường cùng cấp (không có đường nào ưu tiên) trên cùng một mặt bằng.',
  'Đến hết đoạn đường mà nhiều biển báo cấm cùng hết hiệu lực.',
  'Báo trước sắp đến nơi giao nhau cùng mức của các tuyến đường cùng cấp (không có đường nào ưu tiên) trên cùng một mặt bằng.',
  'Đến hết đoạn đường hạn chế tốc độ tối đa.',
  'Báo trước sắp đến đoạn đường do sửa chữa hoặc có trở ngại ở một phía đường mà phải tổ chức đi lại cho phương tiện cả hai chiều trên phía đường còn lại hoặc để báo trước đoạn đường đôi tạm thời hoặc đoạn đường có chiều xe đi và về đi chung.',
  ' Làn đường dành riêng cho xe đạp (kể cả các loại xe thô sơ khác).',
  'Để báo các loại xe (cơ giới và thô sơ) kể cả các xe được ưu tiên theo quy định khi thấy biển số P.132 phải nhường đường cho các loại xe cơ giới đang đi theo hướng ngược lại qua các đoạn đường hẹp hoặc cầu hẹp.',
  'Làn đường dành riêng cho xe máy (kể cả xe gắn máy) và xe đạp (kể cả các loại xe thô sơ khác).',
  'Lan duong danh cho xe otoLàn đường dành cho xe ôtô.',
  'Làn đường dành cho xe buýt.',
  'Làn đường dành riêng cho xe máy và xe gắn máy.',
  'Làn đường dành cho xe ôtô tải. Trong trường hợp cần phân làn các loại xe tải theo khối lượng chuyên chở cho phép thì thì ghi trị số khối lượng chuyên chở cho phép của xe tải lên thân xe trong hình vẽ của biển.',
  'Làn đường dành riêng cho xe ôtô con.',
  'Làn đường dành riêng cho ôtô khách (kể cả ôtô buýt). Trong trường hợp cần phân làn các loại xe khách theo số chỗ ngồi thì ghi số chỗ ngồi cho phép của xe khách lên thân xe trong hình vẽ của biển.',
  'Để báo nơi cấm đỗ xe trừ các xe được ưu tiên theo quy định. Biển số P.131c có hiệu lực cấm các loại xe cơ giới đỗ ở phía đường có đặt biển vào những ngày chẵn.',
  'Để báo nơi cấm đỗ xe trừ các xe được ưu tiên theo quy định. Biển số P.131b có hiệu lực cấm các loại xe cơ giới đỗ ở phía đường có đặt biển vào những ngày lẻ.',
  'Để báo nơi cấm đỗ xe trừ các xe được ưu tiên theo quy định. Biển số P.131a có hiệu lực cấm các loại xe cơ giới đỗ ở phía đường có đặt biển.',
  'Để báo nơi cấm dừng xe và đỗ xe.',
  'Báo hiệu hết đoạn đường dành cho ôtô, xe máy.',
  'Báo hiệu hết đoạn đường dành cho xe ôtô.',
  'Khi quy định tốc độ tối đa cho phép trên từng làn đường. Xe chạy trên làn nào phải tuân thủ tốc độ tối đa cho phép trên làn đường đó.',
  'Để báo hiệu bắt đầu đường dành cho xe máy (kể cả xe gắn máy) và xe đạp (kể cả xe thô sơ).',
  'Để báo hiệu bắt đầu đường dành cho xe máy.',
  'Khi cần phải quy định tốc độ tối đa về ban đêm cho các phương tiện.',
  'Để báo tốc độ tối đa cho phép các xe cơ giới chạy.',
  'Để báo đường dành cho xe thô sơ (kể cả xe của người tàn tật) và người đi bộ. Biển có hiệu lực bắt buộc các loại xe thô sơ (kể cả xe của người tàn tật) và người đi bộ phải dùng đường dành riêng này để đi và cấm các xe cơ giới kể cả xe gắn máy, các xe được ưu tiên theo quy định đi vào đường đã đặt biển này, trừ trường hợp đi cắt ngang qua nhưng phải đảm bảo tuyệt đối an toàn cho xe thô sơ và người đi bộ.',
  'Biển có giá trị báo cho người tham gia giao thông biết hiệu lực của biển số R.306 hết tác dụng, kể từ biển này các xe được phép chạy chậm hơn trị số ghi trên biển nhưng không được gây cản trở các xe khác.',
  'Để báo tốc độ tối thiểu cho phép các xe cơ giới chạy. Biển có hiệu lực bắt buộc các loại xe cơ giới vận hành với tốc độ không nhỏ hơn trị số ghi trên biển trong điều kiện giao thông thuận lợi và an toàn. Các loại xe có tốc độ tối đa theo quy định của nhà sản xuất không đạt tốc độ tối thiểu đã ghi trên biển không được phép đi vào đường này. Trị số ghi trên biển chỉ tốc độ tối thiểu cho phép tính bằng km/h và được quy định tùy theo tiêu chuẩn kỹ thuật của cầu đường và tổ chức giao thông, không được quy định trị số lớn hơn trị số tốc độ an toàn.',
  'Để báo đường dành cho người đi bộ. Biển có hiệu lực bắt buộc người đi bộ phải dung đường dành riêng này để đi. Các loại xe cơ giới và thô sơ (trừ xe đạp và xe lăn dành cho người tàn tật), kể cả các xe được ưu tiên theo quy định không được phép đi vào trên đường đã đặt biển này, trừ trường hợp đi cắt ngang qua nhưng phải đảm bảo tuyệt đối an toàn cho người đi bộ.',
  'Để chỉ đồng thời hai hướng tác dụng (trái và phải). Trên các tuyến đường đối ngoại và các tuyến đường có nhiều người đi lại.',
  'Để chỉ hướng tác dụng của biển là hướng vuông góc với chiều đi. Trên các tuyến đường đối ngoại và các tuyến đường có nhiều người đi lại.',
  'Báo tên đường cho các tuyến đường đối ngoại.',
  'Chỉ dẫn cho người tham gia giao thông biết vị trí và khoảng cách có làn cứu nạn.',
  'Chỉ dẫn sắp vào cầu vượt có tổ chức giao thông liên thông giữa các tuyến.',
  'Chỉ dẫn sắp vào cầu vượt có tổ chức giao thông liên thông giữa các tuyến.',
  'Chỉ dẫn sắp vào cầu vượt có tổ chức giao thông liên thông giữa các tuyến.',
  'Chỉ dẫn sắp vào cầu vượt có tổ chức giao thông liên thông giữa các tuyến.',
  'Báo hiệu nơi đỗ xe dành cho người tàn tật.',
  'Chỉ dẫn sắp vào đoạn đường xuống dốc liên tục, nhằm nhắc nhở lái xe phải đi chậm, đi sát bên phải.',
  'Chỉ dẫn đoạn đường hay xảy ra tai nạn.',
  'Chỉ dẫn người đi đường chú ý khu vực có gió ngang mạnh.',
  'Chỉ dẫn xe lớn hoặc quá khổ đi sát về bên phải, hướng dẫn cho lái xe lớn hoặc quá khổ phải đi tốc độ thấp không được chiếm làn đường của các loại xe khác.',
  'Chỉ dẫn đoạn đường có nền đường yếu, nhắc nhở lái xe đi chậm và cẩn thận.',
  'Chỉ dẫn đoạn đường sương mù, tầm nhìn hạn chế phải đi chậm, tập trung quan sát.',
  'Chỉ dẫn đoạn đường dốc phải đi chậm, lái xe phải cẩn thận.',
  'Chỉ dẫn đoạn đường trơn trượt, phải đi chậm.',
  'Chỉ dẫn cho người đi đường biết hướng vào trạm sửa chữa xe trong khu dịch vụ.',
  'Chỉ dẫn cho người đi đường biết hướng vào trạm dừng nghỉ.',
  'Chỉ dẫn cho người đi đường biết hướng vào ga tàu điện ngầm.',
  'Chỉ dẫn cho người đi đường biết hướng ra bến phà.',
  'Chỉ dẫn cho người đi đường biết hướng vào trạm phục vụ rửa xe.',
  'Chỉ dẫn cho người đi đường biết hướng vào trạm bán xăng dầu.',
  'Chỉ dẫn cho người đi đường biết hướng vào khu danh thắng và du lịch.',
  'Chỉ dẫn cho người đi đường biết hướng vào bến tàu khách.',
  'Chỉ dẫn cho người đi đường biết hướng vào bệnh viện và trạm cấp cứu.',
  'Chỉ dẫn cho người đi đường biết hướng vào bến xe khách đường dài.',
  'Chỉ dẫn cho người đi đường biết hướng vào bãi đậu xe.',
  'Chỉ dẫn cho người đi đường biết hướng vào sân bay.',
  'Chỉ dẫn cho người đi đường biết hướng vào ga xe lửa.',
  'Báo hiệu xe có kéo moóc hoặc xe kéo xe.',
  'Báo sắp đến khu vực có chợ gần đường. Xe cơ giới qua lại khu vực này phải chú ý quan sát, giảm tốc độ.',
  'Báo cho người tham gia giao thông biết phía trước cách 50m có công trường thi công, sửa chữa hoặc nâng cấp.',
  'Báo cho người tham gia giao thông biết phía trước cách 100m có công trường thi công, sửa chữa hoặc nâng cấp.',
  'Báo cho người tham gia giao thông biết phía trước cách 500m có công trường thi công, sửa chữa hoặc nâng cấp.',
  'Chỉ dẫn những đoạn đường đang thi công sửa chữa hoặc nâng cấp cải tạo.',
  'Chỉ các thông tin về một cầu.',
  'Chỉ dẫn nơi đặt trạm cảnh sát giao thông. Các phương tiện phải giảm tốc độ đến mức an toàn và không được vượt khi đi qua khu vực này.',
  'Chỉ dẫn chỗ dừng đỗ xe điện cho khách lên xuống.',
  'Chỉ dẫn chỗ dừng đỗ xe buýt cho khách lên xuống.',
  'Chỉ dẫn chỗ dừng đỗ xe buýt cho khách lên xuống.',
  'Chỉ dẫn sắp đến nơi có nhà trọ.',
  'Chỉ dẫn sắp đến nơi có vị trí cắm trại, nơi tập kết nhà lưu động.',
  'Chỉ dẫn sắp đến nơi tập kết nhà lưu động.',
  'Chỉ dẫn sắp đến nơi có vị trí cắm trại.',
  'Chỉ dẫn nơi nghỉ mát.',
  'Chỉ dẫn nơi có khách sạn phục vụ khách đi đường.',
  'Chỉ dẫn những nơi có các dịch vụ phục vụ khách đi đường (ăn uống nghỉ ngơi, cung cấp nhiên liệu…).',
  'Chỉ dẫn những nơi có đặt trạm điện thoại công cộng chuyên phục vụ khách đi đường.',
  'Chỉ dẫn những nơi có bố trí rửa xe.',
  'Chỉ dẫn những nơi có đặt cửa hàng xăng, dầu hoặc nạp điện phục vụ cho phương tiện giao thông đi trên đường.',
  'Chỉ dẫn nơi đặt trạm kiểm tra tải trọng xe.',
  'Chỉ dẫn nơi đặt xưởng, trạm chuyên phục vụ sửa chữa ôtô, xe máy hỏng trên đường.',
  'Chỉ dẫn nơi có trạm cấp cứu y tế ở gần đường.',
  'Chỉ dẫn sắp đến cơ sở điều trị bệnh ở gần đường như bệnh viện, bệnh xá, trạm xá v.v...',
  'Chỉ dẫn cho người đi bộ sử dụng hầm chui qua đường.',
  'Chỉ dẫn cho người đi bộ sử dụng hầm chui qua đường.',
  'Chỉ dẫn cho người đi bộ sử dụng cầu vượt qua đường.',
  'Chỉ dẫn cho người đi bộ sử dụng cầu vượt qua đường.',
  'Chỉ dẫn cho người đi bộ và người lái xe biết nơi bắt đầu đoạn đường dành cho người đi bộ.',
  'Chỉ dẫn người đi bộ và người tham gia giao thông biết vị trí dành cho người đi bộ sang ngang.',
  'Chỉ dẫn người đi bộ và người tham gia giao thông biết vị trí dành cho người đi bộ sang ngang.',
  'Chỉ dẫn những nơi có di tích lịch sử hoặc những nơi có danh lam thắng cảnh, những nơi có thể tham quan v.v... ở hai ven đường',
  'Chỉ dẫn những nơi có di tích lịch sử hoặc những nơi có danh lam thắng cảnh, những nơi có thể tham quan v.v... ở hai ven đường.',
  'Chỉ dẫn địa giới hành chính giữa các thành phố, tỉnh, huyện. Đặt trên các tuyến đường quốc lộ, đường tỉnh...',
  'Chỉ dẫn địa giới hành chính giữa các thành phố, tỉnh, huyện. Áp dụng cho các tuyến đường đối ngoại và các tuyến đường có nhiều người nước ngoài đi lại.',
  'Chỉ lối đi ở các nơi đường giao nhau bị cấm rẽ.',
  'Chỉ hướng đường phải đi cho từng loại xe ghi trên biển đến một khu dân cư tiếp theo.',
  'Chỉ hướng đường phải đi cho từng loại xe ghi trên biển đến một khu dân cư tiếp theo.',
  'Chỉ hướng đường phải đi cho từng loại xe ghi trên biển đến một khu dân cư tiếp theo.',
  'Chỉ dẫn lối đi đường tránh, đường vòng trong trường hợp đường chính bị tắc hoặc đường chính cấm một số loại xe đi qua.',
  'Chỉ dẫn hướng đi đến một địa danh lân cận tiếp theo và khoảng cách (làm tròn đến km) đến nơi đó.',
  'Để báo đường cấm xe thô sơ, chuyển động do người kéo, đẩy đi qua. Biển không có giá trị cấm những xe nôi của trẻ em và phương tiện chuyên dùng để đi lại của những người tàn tật.',
  'Để báo các xe (cơ giới và thô sơ) dừng lại.',
  'Để báo đường cấm người đi bộ qua lại.',
  'Để báo đường cấm xe ba bánh loại không có động cơ như xe xích lô, xe lôi đạp, v.v... ',
  'Để báo đường cấm xe ba bánh loại có động cơ như xe lam, xe xích lô máy, xe lôi máy, v.v...',
  'Đến hết đoạn đường hạn chế tốc độ tối đa cho phép.',
  'Để báo đường cấm xe máy và xe gắn máy đi qua.',
  'Để báo đường cấm xe đạp thồ đi qua. Biển này không cấm người dắt loại xe này.',
  'Để báo đường cấm xe đạp đi qua. Biển không có giá trị cấm những người dắt xe đạp.',
  'Để báo đường cấm các loại máy kéo, kể cả máy kéo bánh hơi và bánh xích đi qua.',
  'Để báo đường cấm các loại xe sơ-mi-rơ-moóc và các xe kéo rơ- moóc trừ các xe được ưu tiên (có dạng xe sơ-mi-rơ-moóc hoặc có kéo theo rơ-moóc) theo quy định.',
  'Để báo cấm các loại xe cơ giới kéo theo rơ-moóc kể cả xe máy, máy kéo, ôtô khách kéo theo rơ-moóc đi lại, trừ loại ôtô sơ-mi-rơ-moóc và các xe được ưu tiên (có kéo theo rơ-moóc) theo quy định.',
  'Để báo cấm xe ôtô taxi đi lại. Trường hợp cấm xe ôtô taxi theo giờ thì đặt biển phụ ghi giờ cấm.',
  'Để báo cấm ôtô chở khách đi qua trừ các xe ưu tiên theo quy định. Biển này không cấm xe buýt.',
  'Để báo đường cấm xe ôtô chở khách và các loại xe ôtô tải kể cả các loại máy kéo và xe máy thi công chuyên dùng đi qua trừ các xe được ưu tiên theo quy định.',
  'Để báo đường cấm các xe chở hàng nguy hiểm.',
  'Để báo đường cấm các loại xe ôtô tải có khối lượng chuyên chở (theo Giấy chứng nhận kiểm định an toàn kỹ thuật và bảo vệ môi trường phương tiện giao thông cơ giới đường bộ) lớn hơn một giá trị nhất định, phải đặt biển số P.106b. Biển có hiệu lực cấm các xe ô tô tải có khối lượng chuyên chở (xác định theo Giấy chứng nhận kiểm định an toàn kỹ thuật và bảo vệ môi trường phương tiện giao thông cơ giới đường bộ) lớn hơn giá trị chữ số ghi trong biển (chữ số tấn ghi bằng màu trắng trên hình vẽ xe). Biển có hiệu lực cấm đối với cả máy kéo và các xe máy chuyên dùng đi vào đoạn đường đặt biển.',
  'Biển có hiệu lực cấm đối với cả máy kéo và các xe máy chuyên dùng đi vào đoạn đường đặt biển số P.106a.',
  'Để báo cấm xe ôtô quay đầu (theo kiểu chữ U). Chiều mũi tên phù hợp với chiều cấm xe ô tô quay đầu. Biển số P.124b có hiệu lực cấm xe ôtô và xe máy 3 bánh (side car) quay đầu (theo kiểu chữ U) trừ các xe được ưu tiên theo quy định. Biển không có giá trị cấm rẽ trái để đi sang hướng đường khác.',
  'Biển không có giá trị cấm những người dắt xe máy.',
  'Để báo đường cấm các loại xe cơ giới kể cả xe máy 3 bánh có thùng rẽ phải hay rẽ trái, trừ xe máy 2 bánh, xe gắn máy và các xe được ưu tiên theo quy định,',
  'Để báo đường cấm các loại xe cơ giới kể cả xe máy 3 bánh có thùng rẽ phải hay rẽ trái, trừ xe máy 2 bánh, xe gắn máy và các xe được ưu tiên theo quy định.',
  'Để báo đường cấm các loại xe cơ giới kể cả xe máy 3 bánh có thùng đi qua, trừ xe máy 2 bánh, xe gắn máy và các xe được ưu tiên theo quy định.'];